alias gs='GIT_TRACE=1 git status -sb'
alias gst='GIT_TRACE=1 git status'
alias ga='GIT_TRACE=1 git add'
alias gaa='GIT_TRACE=1 git add .'
alias gb='GIT_TRACE=1 git branch'
alias gc='GIT_TRACE=1 git commit'
alias gco='GIT_TRACE=1 git checkout'
alias gcb='GIT_TRACE=1 git checkout -b'
alias gcm='GIT_TRACE=1 git commit -m'
alias gca='GIT_TRACE=1 git commit --amend'
alias gp='GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_TRACE_PERFORMANCE=1 git push'
alias gpf='GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_TRACE_PERFORMANCE=1 git push -f'
alias gl='GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_CURL_VERBOSE=1 git pull --rebase'
alias gm='GIT_TRACE=1 git merge'
alias grb='GIT_TRACE=1 git rebase'
alias gd='GIT_TRACE=1 git diff'
alias gds='GIT_TRACE=1 git diff --staged'
alias gr='GIT_TRACE=1 git restore'
alias grs='GIT_TRACE=1 git reset'
alias grh='GIT_TRACE=1 git reset --hard'
alias gt='GIT_TRACE=1 git tag'
alias gstash='GIT_TRACE=1 git stash'
alias gsta='GIT_TRACE=1 git stash apply'
alias gpop='GIT_TRACE=1 git stash pop'
alias gclean='GIT_TRACE=1 git clean -fd'
alias glgc='GIT_TRACE=1 git log --oneline --graph --decorate'
alias glga='git log --graph --decorate --all --format="%C(auto)%h %Cgreen(%cr)%Creset %C(bold blue)<%an>%Creset %C(auto)%d %s"'
